# Generated by Django 3.2.6 on 2024-02-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club')),
            ],
            options={
                'verbose_name_plural': 'Image',
                'db_table': 'Image',
            },
        ),
    ]
