# Generated by Django 3.2.6 on 2024-02-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clubimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimage',
            name='image',
            field=models.ImageField(upload_to='club_images/'),
        ),
    ]
