# Generated by Django 3.2.6 on 2024-02-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_clubimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubimage',
            options={'verbose_name_plural': 'ClubImage'},
        ),
        migrations.AlterModelTable(
            name='clubimage',
            table='ClubImage',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club')),
            ],
            options={
                'verbose_name_plural': 'EventImage',
                'db_table': 'EventImage',
            },
        ),
    ]
