# Generated by Django 3.2.6 on 2024-02-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240206_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='expire_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Facilities',
            new_name='facilities',
        ),
    ]
