# Generated by Django 3.2.6 on 2024-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240206_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='club_images/'),
        ),
    ]
