# Generated by Django 3.2.6 on 2024-02-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_clubimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimage',
            name='image',
            field=models.ImageField(upload_to='club_images/'),
        ),
    ]
