# Generated by Django 3.2.6 on 2024-02-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfile'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
