# Generated by Django 3.2.6 on 2024-02-26 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 26, 21, 58, 58, 504080)),
        ),
    ]
